name: gitleaks

on:
  pull_request:

jobs:
  reviewdog:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-gitleaks@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: warning
          fail_on_error: true
