name: lint

on:
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-22.04
    permissions:
      checks: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: error
          fail_on_error: false
          reporter: github-pr-review
          eslint_flags: "src/"
